export const SET_REPORT_INSTANCES = 'SET_REPORT_INSTANCES';
export const SET_REPORT_TEMPLATES = 'SET_REPORT_TEMPLATES';
export const READED_REPORT_INSTANCE = 'READED_REPORT_INSTANCE';
export const TOGGLE_PURGE = 'TOGGLE_PURGE';
