# Docker compose file to manage your deployed images.
# Use MySQL server 5.7 and latest Scada-LTS local build.
# Using attached webapps folder as developer you will be able to modify the static content from host os.
# Attach shell to stop the tomcat instance and then you will be able to run in JPDA mode.
version: '3'
services: 
    database:
        container_name: mysql
        image: biarms/mysql:5.7
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=scadalts
    scadalts:
        image: scadalts/scadalts:latest
        ports: 
            - "8080:8080"
        depends_on: 
            - database
        links:
            - database:database