# Docker compose file to manage your deployed images.
# Use MySQL server 5.7 and latest Scada-LTS local build.
# Using attached webapps folder as developer you will be able to modify the static content from host os.
# Attach shell to stop the tomcat instance and then you will be able to run in JPDA mode.
version: '3'
services: 
    database:
        container_name: mysql
        image: mysql/mysql-server:5.7
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3306"]
        volumes:
            -   ./docker/volumes/databases:/home/
    scadalts:
        image: scadalts/scadalts:latest
        environment:
            - CATALINA_OPTS=-Xmx512m -Xms512m
        ports: 
            - "8080:8080"
        depends_on: 
            - database
        expose: ["8080", "8000"]
        links:
            - database:database
        command:
          - /usr/bin/wait-for-it
          - --host=database
          - --port=3306
          - --timeout=30
          - --strict
          - --
          - /usr/local/tomcat/bin/catalina.sh
          - run
