package com.serotonin.mango.vo.dataSource.bacnet;

import com.serotonin.bacnet4j.type.enumerated.EngineeringUnits;

import java.util.stream.Stream;

public enum BACnetEngineeringUnits {

    METERS_PER_SECOND_PER_SECOND(EngineeringUnits.metersPerSecondPerSecond, "m/s\u00B2"),
    SQUARE_METERS(EngineeringUnits.squareMeters, "m\u00B2"),
    SQUARE_CENTIMETERS(EngineeringUnits.squareCentimeters, "cm\u00B2"),
    SQUARE_FEET(EngineeringUnits.squareFeet, "ft\u00B2"),
    SQUARE_INCHES(EngineeringUnits.squareInches, "in\u00B2"),
    CURRENCY1(EngineeringUnits.currency1, "$"),
    CURRENCY2(EngineeringUnits.currency2, "\u20AC"),
    CURRENCY3(EngineeringUnits.currency3, "\u00A3"),
    CURRENCY4(EngineeringUnits.currency4, "\u00A5"),
    CURRENCY5(EngineeringUnits.currency5, "\u20BD"),
    CURRENCY6(EngineeringUnits.currency6, "kr"),
    CURRENCY7(EngineeringUnits.currency7, "Rs"),
    CURRENCY8(EngineeringUnits.currency8, "R$"),
    CURRENCY9(EngineeringUnits.currency9, "\u20A9"),
    CURRENCY10(EngineeringUnits.currency10, "CHF"),
    MILLIAMPERES(EngineeringUnits.milliamperes, "mA"),
    AMPERES(EngineeringUnits.amperes, "A"),
    AMPERES_PER_METER(EngineeringUnits.amperesPerMeter, "A/m"),
    AMPERES_PER_SQUARE_METER(EngineeringUnits.amperesPerSquareMeter, "A/m\u00B2"),
    AMPERE_SQUARE_METERS(EngineeringUnits.ampereSquareMeters, "A\u00B7m\u00B2"),
    FARADS(EngineeringUnits.farads, "F"),
    HENRYS(EngineeringUnits.henrys, "H"),
    OHMS(EngineeringUnits.ohms, "\u03A9"),
    OHM_METERS(EngineeringUnits.ohmMeters, "\u03A9\u00B7m"),
    MILLIOHMS(EngineeringUnits.milliohms, "m\u03A9"),
    KILOHMS(EngineeringUnits.kilohms, "k\u03A9"),
    MEGOHMS(EngineeringUnits.megohms, "M\u03A9"),
    SIEMENS(EngineeringUnits.siemens, "S"),
    SIEMENS_PER_METER(EngineeringUnits.siemensPerMeter, "S/m"),
    TESLAS(EngineeringUnits.teslas, "T"),
    VOLTS(EngineeringUnits.volts, "V"),
    MILLIVOLTS(EngineeringUnits.millivolts, "mV"),
    KILOVOLTS(EngineeringUnits.kilovolts, "kV"),
    MEGAVOLTS(EngineeringUnits.megavolts, "MV"),
    VOLT_AMPERES(EngineeringUnits.voltAmperes, "VA"),
    KILOVOLT_AMPERES(EngineeringUnits.kilovoltAmperes, "kVA"),
    MEGAVOLT_AMPERES(EngineeringUnits.megavoltAmperes, "MVA"),
    VOLT_AMPERES_REACTIVE(EngineeringUnits.voltAmperesReactive, "var"),
    KILOVOLT_AMPERES_REACTIVE(EngineeringUnits.kilovoltAmperesReactive, "kvar"),
    MEGAVOLT_AMPERES_REACTIVE(EngineeringUnits.megavoltAmperesReactive, "Mvar"),
    VOLTS_PER_DEGREE_KELVIN(EngineeringUnits.voltsPerDegreeKelvin, "V/K"),
    VOLTS_PER_METER(EngineeringUnits.voltsPerMeter, "V/m"),
    DEGREES_PHASE(EngineeringUnits.degreesPhase, "\u00B0"),
    POWER_FACTOR(EngineeringUnits.powerFactor, ""),
    WEBERS(EngineeringUnits.webers, "Wb"),
    JOULES(EngineeringUnits.joules, "J"),
    KILOJOULES(EngineeringUnits.kilojoules, "kJ"),
    KILOJOULES_PER_KILOGRAM(EngineeringUnits.kilojoulesPerKilogram, "kJ/kg"),
    MEGAJOULES(EngineeringUnits.megajoules, "MJ"),
    WATT_HOURS(EngineeringUnits.wattHours, "Wh"),
    KILOWATT_HOURS(EngineeringUnits.kilowattHours, "kWh"),
    MEGAWATT_HOURS(EngineeringUnits.megawattHours, "MWh"),
    BTUS(EngineeringUnits.btus, "BTU"),
    KILO_BTUS(EngineeringUnits.kiloBtus, "kBTU"),
    MEGA_BTUS(EngineeringUnits.megaBtus, "MBTU"),
    THERMS(EngineeringUnits.therms, "therm"),
    TON_HOURS(EngineeringUnits.tonHours, "ton h"),
    JOULES_PER_KILOGRAM_DRY_AIR(EngineeringUnits.joulesPerKilogramDryAir, "J/kg dry air"),
    KILOJOULES_PER_KILOGRAM_DRY_AIR(EngineeringUnits.kilojoulesPerKilogramDryAir, "kJ/kg dry air"),
    MEGAJOULES_PER_KILOGRAM_DRY_AIR(EngineeringUnits.megajoulesPerKilogramDryAir, "MJ/kg dry air"),
    BTUS_PER_POUND_DRY_AIR(EngineeringUnits.btusPerPoundDryAir, "BTU/lb dry air"),
    BTUS_PER_POUND(EngineeringUnits.btusPerPound, "BTU/lb"),
    JOULES_PER_DEGREE_KELVIN(EngineeringUnits.joulesPerDegreeKelvin, "J/K"),
    KILOJOULES_PER_DEGREE_KELVIN(EngineeringUnits.kilojoulesPerDegreeKelvin, "kJ/K"),
    MEGAJOULES_PER_DEGREE_KELVIN(EngineeringUnits.megajoulesPerDegreeKelvin, "MJ/K"),
    JOULES_PER_KILOGRAM_DEGREE_KELVIN(EngineeringUnits.joulesPerKilogramDegreeKelvin, "J/(kg\u00B7K)"),
    NEWTON(EngineeringUnits.newton, "N"),
    CYCLES_PER_HOUR(EngineeringUnits.cyclesPerHour, "cph"),
    CYCLES_PER_MINUTE(EngineeringUnits.cyclesPerMinute, "cpm"),
    HERTZ(EngineeringUnits.hertz, "Hz"),
    KILOHERTZ(EngineeringUnits.kilohertz, "kHz"),
    MEGAHERTZ(EngineeringUnits.megahertz, "MHz"),
    PER_HOUR(EngineeringUnits.perHour, "1/h"),
    GRAMS_OF_WATER_PER_KILOGRAM_DRY_AIR(EngineeringUnits.gramsOfWaterPerKilogramDryAir, "g/kg dry air"),
    PERCENT_RELATIVE_HUMIDITY(EngineeringUnits.percentRelativeHumidity, "%"),
    MILLIMETERS(EngineeringUnits.millimeters, "mm"),
    CENTIMETERS(EngineeringUnits.centimeters, "cm"),
    METERS(EngineeringUnits.meters, "m"),
    INCHES(EngineeringUnits.inches, "in"),
    FEET(EngineeringUnits.feet, "ft"),
    CANDELAS(EngineeringUnits.candelas, "cd"),
    CANDELAS_PER_SQUARE_METER(EngineeringUnits.candelasPerSquareMeter, "cd/m\u00B2"),
    WATTS_PER_SQUARE_FOOT(EngineeringUnits.wattsPerSquareFoot, "W/ft\u00B2"),
    WATTS_PER_SQUARE_METER(EngineeringUnits.wattsPerSquareMeter, "W/m\u00B2"),
    LUMENS(EngineeringUnits.lumens, "lm"),
    LUXES(EngineeringUnits.luxes, "lx"),
    FOOT_CANDLES(EngineeringUnits.footCandles, "fc"),
    KILOGRAMS(EngineeringUnits.kilograms, "kg"),
    POUNDS_MASS(EngineeringUnits.poundsMass, "lb"),
    TONS(EngineeringUnits.tons, "t"),
    GRAMS_PER_SECOND(EngineeringUnits.gramsPerSecond, "g/s"),
    GRAMS_PER_MINUTE(EngineeringUnits.gramsPerMinute, "g/min"),
    KILOGRAMS_PER_SECOND(EngineeringUnits.kilogramsPerSecond, "kg/s"),
    KILOGRAMS_PER_MINUTE(EngineeringUnits.kilogramsPerMinute, "kg/min"),
    KILOGRAMS_PER_HOUR(EngineeringUnits.kilogramsPerHour, "kg/h"),
    POUNDS_MASS_PER_SECOND(EngineeringUnits.poundsMassPerSecond, "lb/s"),
    POUNDS_MASS_PER_MINUTE(EngineeringUnits.poundsMassPerMinute, "lb/min"),
    POUNDS_MASS_PER_HOUR(EngineeringUnits.poundsMassPerHour, "lb/h"),
    TONS_PER_HOUR(EngineeringUnits.tonsPerHour, "t/h"),
    MILLIWATTS(EngineeringUnits.milliwatts, "mW"),
    WATTS(EngineeringUnits.watts, "W"),
    KILOWATTS(EngineeringUnits.kilowatts, "kW"),
    MEGAWATTS(EngineeringUnits.megawatts, "MW"),
    BTUS_PER_HOUR(EngineeringUnits.btusPerHour, "BTU/h"),
    KILO_BTUS_PER_HOUR(EngineeringUnits.kilogramsPerHour, "kBTU/h"),
    HORSEPOWER(EngineeringUnits.horsepower, "hp"),
    TONS_REFRIGERATION(EngineeringUnits.tonsRefrigeration, "TR"),
    PASCALS(EngineeringUnits.pascals, "Pa"),
    HECTOPASCALS(EngineeringUnits.hectopascals, "hPa"),
    KILOPASCALS(EngineeringUnits.kilopascals, "kPa"),
    MILLIBARS(EngineeringUnits.millibars, "mbar"),
    BARS(EngineeringUnits.bars, "bar"),
    POUNDS_FORCE_PER_SQUARE_INCH(EngineeringUnits.poundsForcePerSquareInch, "psi"),
    CENTIMETERS_OF_WATER(EngineeringUnits.centimetersOfWater, "cm H\u2082O"),
    INCHES_OF_WATER(EngineeringUnits.inchesOfWater, "in H\u2082O"),
    MILLIMETERS_OF_MERCURY(EngineeringUnits.millimetersOfMercury, "mmHg"),
    CENTIMETERS_OF_MERCURY(EngineeringUnits.centimetersOfMercury, "cmHg"),
    INCHES_OF_MERCURY(EngineeringUnits.inchesOfMercury, "inHg"),
    DEGREES_CELSIUS(EngineeringUnits.degreesCelsius, "\u00B0C"),
    DEGREES_KELVIN(EngineeringUnits.degreesKelvin, "K"),
    DEGREES_KELVIN_PER_HOUR(EngineeringUnits.degreesKelvinPerHour, "K/h"),
    DEGREES_KELVIN_PER_MINUTE(EngineeringUnits.degreesKelvinPerMinute, "K/min"),
    DEGREES_FAHRENHEIT(EngineeringUnits.degreesFahrenheit, "\u00B0F"),
    DEGREE_DAYS_CELSIUS(EngineeringUnits.degreeDaysCelsius, "\u00B0C d"),
    DEGREE_DAYS_FAHRENHEIT(EngineeringUnits.degreeDaysFahrenheit, "\u00B0F d"),
    DELTA_DEGREES_FAHRENHEIT(EngineeringUnits.deltaDegreesFahrenheit, "\u0394\u00B0F"),
    DELTA_DEGREES_KELVIN(EngineeringUnits.deltaDegreesKelvin, "\u0394K"),
    YEARS(EngineeringUnits.years, "yr"),
    MONTHS(EngineeringUnits.months, "mo"),
    WEEKS(EngineeringUnits.weeks, "wk"),
    DAYS(EngineeringUnits.days, "d"),
    HOURS(EngineeringUnits.hours, "h"),
    MINUTES(EngineeringUnits.minutes, "min"),
    SECONDS(EngineeringUnits.seconds, "s"),
    HUNDREDTHS_SECONDS(EngineeringUnits.hundredthsSeconds, "cs"),
    MILLISECONDS(EngineeringUnits.milliseconds, "ms"),
    NEWTON_METERS(EngineeringUnits.newtonMeters, "N\u00B7m"),
    MILLIMETERS_PER_SECOND(EngineeringUnits.millimetersPerSecond, "mm/s"),
    MILLIMETERS_PER_MINUTE(EngineeringUnits.millimetersPerMinute, "mm/min"),
    METERS_PER_SECOND(EngineeringUnits.metersPerSecond, "m/s"),
    METERS_PER_MINUTE(EngineeringUnits.metersPerMinute, "m/min"),
    METERS_PER_HOUR(EngineeringUnits.metersPerHour, "m/h"),
    KILOMETERS_PER_HOUR(EngineeringUnits.kilometersPerHour, "km/h"),
    FEET_PER_SECOND(EngineeringUnits.feetPerSecond, "ft/s"),
    FEET_PER_MINUTE(EngineeringUnits.feetPerMinute, "ft/min"),
    MILES_PER_HOUR(EngineeringUnits.milesPerHour, "mph"),
    CUBIC_FEET(EngineeringUnits.cubicFeet, "ft\u00B3"),
    CUBIC_METERS(EngineeringUnits.cubicMeters, "m\u00B3"),
    IMPERIAL_GALLONS(EngineeringUnits.imperialGallons, "imp gal"),
    LITERS(EngineeringUnits.liters, "L"),
    US_GALLONS(EngineeringUnits.usGallons, "US gal"),
    CUBIC_FEET_PER_SECOND(EngineeringUnits.cubicFeetPerSecond, "ft\u00B3/s"),
    CUBIC_FEET_PER_MINUTE(EngineeringUnits.cubicFeetPerMinute, "ft\u00B3/min"),
    CUBIC_METERS_PER_SECOND(EngineeringUnits.cubicMetersPerSecond, "m\u00B3/s"),
    CUBIC_METERS_PER_MINUTE(EngineeringUnits.cubicMetersPerMinute, "m\u00B3/min"),
    CUBIC_METERS_PER_HOUR(EngineeringUnits.cubicMetersPerHour, "m\u00B3/h"),
    IMPERIAL_GALLONS_PER_MINUTE(EngineeringUnits.imperialGallonsPerMinute, "imp gal/min"),
    LITERS_PER_SECOND(EngineeringUnits.litersPerSecond, "L/s"),
    LITERS_PER_MINUTE(EngineeringUnits.litersPerMinute, "L/min"),
    LITERS_PER_HOUR(EngineeringUnits.litersPerHour, "L/h"),
    US_GALLONS_PER_MINUTE(EngineeringUnits.usGallonsPerMinute, "US gal/min"),
    DEGREES_ANGULAR(EngineeringUnits.degreesAngular, "\u00B0"),
    DEGREES_CELSIUS_PER_HOUR(EngineeringUnits.degreesCelsiusPerHour, "\u00B0C/h"),
    DEGREES_CELSIUS_PER_MINUTE(EngineeringUnits.degreesCelsiusPerMinute, "\u00B0C/min"),
    DEGREES_FAHRENHEIT_PER_HOUR(EngineeringUnits.degreesFahrenheitPerHour, "\u00B0F/h"),
    DEGREES_FAHRENHEIT_PER_MINUTE(EngineeringUnits.degreesFahrenheitPerMinute, "\u00B0F/min"),
    JOULE_SECONDS(EngineeringUnits.jouleSeconds, "J\u00B7s"),
    KILOGRAMS_PER_CUBIC_METER(EngineeringUnits.kilogramsPerCubicMeter, "kg/m\u00B3"),
    KILOWATT_HOURS_PER_SQUARE_METER(EngineeringUnits.kilowattHoursPerSquareMeter, "kWh/m\u00B2"),
    KILOWATT_HOURS_PER_SQUARE_FOOT(EngineeringUnits.kilowattHoursPerSquareFoot, "kWh/ft\u00B2"),
    MEGAJOULES_PER_SQUARE_METER(EngineeringUnits.megajoulesPerSquareMeter, "MJ/m\u00B2"),
    MEGAJOULES_PER_SQUARE_FOOT(EngineeringUnits.megajoulesPerSquareFoot, "MJ/ft\u00B2"),
    NO_UNITS(EngineeringUnits.noUnits, ""),
    NEWTON_SECONDS(EngineeringUnits.newtonSeconds, "N\u00B7s"),
    NEWTONS_PER_METER(EngineeringUnits.newtonsPerMeter, "N/m"),
    PARTS_PER_MILLION(EngineeringUnits.partsPerMillion, "ppm"),
    PARTS_PER_BILLION(EngineeringUnits.partsPerBillion, "ppb"),
    PERCENT(EngineeringUnits.percent, "%"),
    PERCENT_OBSCURATION_PER_FOOT(EngineeringUnits.percentObscurationPerFoot, "%/ft"),
    PERCENT_OBSCURATION_PER_METER(EngineeringUnits.percentObscurationPerMeter, "%/m"),
    PERCENT_PER_SECOND(EngineeringUnits.percentPerSecond, "%/s"),
    PER_MINUTE(EngineeringUnits.perMinute, "1/min"),
    PER_SECOND(EngineeringUnits.perSecond, "1/s"),
    PSI_PER_DEGREE_FAHRENHEIT(EngineeringUnits.psiPerDegreeFahrenheit, "psi/\u00B0F"),
    RADIANS(EngineeringUnits.radians, "rad"),
    RADIANS_PER_SECOND(EngineeringUnits.radiansPerSecond, "rad/s"),
    REVOLUTIONS_PER_MINUTE(EngineeringUnits.revolutionsPerMinute, "rpm"),
    SQUARE_METERS_PER_NEWTON(EngineeringUnits.squareMetersPerNewton, "m\u00B2/N"),
    WATTS_PER_METER_PER_DEGREE_KELVIN(EngineeringUnits.wattsPerMeterPerDegreeKelvin, "W/m\u00B7K"),
    WATTS_PER_SQUARE_METER_DEGREE_KELVIN(EngineeringUnits.wattsPerSquareMeterDegreeKelvin, "W/m\u00B2\u00B7K");

    private final EngineeringUnits engineeringUnits;
    private final String suffix;

    BACnetEngineeringUnits(EngineeringUnits engineeringUnits, String suffix) {
        this.engineeringUnits = engineeringUnits;
        this.suffix = suffix;
    }

    public int getValue() {
        return engineeringUnits.intValue();
    }

    public String getName() {
        return engineeringUnits.toString();
    }

    public String getSuffix() {
        return "[" + suffix + "]";
    }

    public static BACnetEngineeringUnits valueOf(int value) {
        return Stream.of(BACnetEngineeringUnits.values())
                .filter(unit -> unit.getValue() == value)
                .findAny()
                .orElse(NO_UNITS);
    }

    @Override
    public String toString() {
        return suffix;
    }
}