openapi: 3.0.0
servers:
  - url: 'http://localhost:8080/ScadaBR/api'
    description: 'Scada development Server'
    variables: {}
info:
  version: 2.7.5
  title: Scada-LTS API
  description: 'Scada-LTS OpenAPI Specification. Description contains only a SMS and Email new feature REST API'
  termsOfService: ''
  contact:
    name: 'Kamil Jarmusik - SoftQ Developer'
    email: 'kamil.jarmusik@softq.pl'
  license:
    name: 'GPL-2.0'
paths:
  /work-items/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items not executed'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/group-by/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Grouping work items not executed by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/executed/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items executed'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/executed/group-by/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Grouping work items executed by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/failed/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items fail executed'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/failed/group-by/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Grouping work items fail executed by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/running/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items running'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/running/group-by/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Grouping work items running by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/success/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items success executed'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/success/group-by/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Grouping work items success executed by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/all/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items executed and not executed'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/all/group-by/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Grouping work items all by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/group-by/all/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Grouping work items all by class - DEPRECATED'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/limit/{limit}/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Set limit for work items map - NOT WORKING DEPRECATED'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
      parameters:
        - name: 'limit'
          in: 'path'
          required: true
          schema:
            type: 'integer'
  /work-items/longer/{executedMs}/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items executed longer than executedMs'
      responses:
        '200':
          description: "Get successful"
          headers: { }
      parameters:
        - name: 'executedMs'
          in: 'path'
          required: true
          schema:
            type: 'integer'
  /work-items/longer/{executedMs}/group-by/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items executed longer than executedMs by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
      parameters:
        - name: 'executedMs'
          in: 'path'
          required: true
          schema:
            type: 'integer'
  /work-items/less/{executedMs}/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items executed less than executedMs'
      responses:
        '200':
          description: "Get successful"
          headers: { }
      parameters:
        - name: 'executedMs'
          in: 'path'
          required: true
          schema:
            type: 'integer'
  /work-items/less/{executedMs}/group-by/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items executed less than executedMs by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
      parameters:
        - name: 'executedMs'
          in: 'path'
          required: true
          schema:
            type: 'integer'
  /work-items/priority/{priority}/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items all filtering by priority'
      responses:
        '200':
          description: "Get successful"
          headers: { }
      parameters:
        - name: 'priority'
          in: 'path'
          required: true
          schema:
            type: 'string'
            enum: [ HIGH, MEDIUM, LOW ]
  /work-items/priority/{priority}/group-by/:
    get:
      tags:
        - WorkItemInfoAPI
      description: 'Get work items all filtering by priority grouping by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
      parameters:
        - name: 'priority'
          in: 'path'
          required: true
          schema:
            type: 'string'
            enum: [ HIGH, MEDIUM, LOW ]
  /work-items/scheduled/:
    get:
      tags:
        - ScheduledWorkItemInfoAPI
      description: 'Get active scheduled work items'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/scheduled/group-by/:
    get:
      tags:
        - ScheduledWorkItemInfoAPI
      description: 'Grouping active scheduled work items by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
  /work-items/scheduled/state/{state}/:
    get:
      tags:
        - ScheduledWorkItemInfoAPI
      description: 'Get active scheduled work items'
      responses:
        '200':
          description: "Get successful"
          headers: { }
      parameters:
        - name: 'state'
          in: 'path'
          required: true
          schema:
            type: 'string'
            enum: [ VIRGIN, CANCELLED, EXECUTED, SCHEDULED ]
  /work-items/scheduled/state/{state}/group-by/:
    get:
      tags:
        - ScheduledWorkItemInfoAPI
      description: 'Grouping active scheduled work items by class'
      responses:
        '200':
          description: "Get successful"
          headers: { }
      parameters:
        - name: 'state'
          in: 'path'
          required: true
          schema:
            type: 'string'
            enum: [ VIRGIN, CANCELLED, EXECUTED, SCHEDULED ]

