package com.serotonin.mango.vo;

import com.serotonin.bacnet4j.type.enumerated.EngineeringUnits;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

@RunWith(Parameterized.class)
public class EngineeringUnitsTypesTest {

    @Parameterized.Parameters(name= "{index}: unit: {0}, expected: {1}")
    public static Object[][] data() {
        return new Object[][] {
                {EngineeringUnitsTypes.Acceleration.METERS_PER_SECOND_PER_SECOND, EngineeringUnits.metersPerSecondPerSecond},
                {EngineeringUnitsTypes.Area.SQUARE_METERS, EngineeringUnits.squareMeters},
                {EngineeringUnitsTypes.Area.SQUARE_CENTIMETERS, EngineeringUnits.squareCentimeters},
                {EngineeringUnitsTypes.Area.SQUARE_FEET, EngineeringUnits.squareFeet},
                {EngineeringUnitsTypes.Area.SQUARE_INCHES, EngineeringUnits.squareInches},
                {EngineeringUnitsTypes.Currency.CURRENCY1, EngineeringUnits.currency1},
                {EngineeringUnitsTypes.Currency.CURRENCY2, EngineeringUnits.currency2},
                {EngineeringUnitsTypes.Currency.CURRENCY3, EngineeringUnits.currency3},
                {EngineeringUnitsTypes.Currency.CURRENCY4, EngineeringUnits.currency4},
                {EngineeringUnitsTypes.Currency.CURRENCY5, EngineeringUnits.currency5},
                {EngineeringUnitsTypes.Currency.CURRENCY6, EngineeringUnits.currency6},
                {EngineeringUnitsTypes.Currency.CURRENCY7, EngineeringUnits.currency7},
                {EngineeringUnitsTypes.Currency.CURRENCY8, EngineeringUnits.currency8},
                {EngineeringUnitsTypes.Currency.CURRENCY9, EngineeringUnits.currency9},
                {EngineeringUnitsTypes.Currency.CURRENCY10, EngineeringUnits.currency10},
                {EngineeringUnitsTypes.Electrical.MILLIAMPERES, EngineeringUnits.milliamperes},
                {EngineeringUnitsTypes.Electrical.AMPERES, EngineeringUnits.amperes},
                {EngineeringUnitsTypes.Electrical.AMPERES_PER_METER, EngineeringUnits.amperesPerMeter},
                {EngineeringUnitsTypes.Electrical.AMPERES_PER_SQUARE_METER, EngineeringUnits.amperesPerSquareMeter},
                {EngineeringUnitsTypes.Electrical.AMPERE_SQUARE_METERS, EngineeringUnits.ampereSquareMeters},
                {EngineeringUnitsTypes.Electrical.FARADS, EngineeringUnits.farads},
                {EngineeringUnitsTypes.Electrical.HENRYS, EngineeringUnits.henrys},
                {EngineeringUnitsTypes.Electrical.OHMS, EngineeringUnits.ohms},
                {EngineeringUnitsTypes.Electrical.OHM_METERS, EngineeringUnits.ohmMeters},
                {EngineeringUnitsTypes.Electrical.MILLIOHMS, EngineeringUnits.milliohms},
                {EngineeringUnitsTypes.Electrical.KILOHMS, EngineeringUnits.kilohms},
                {EngineeringUnitsTypes.Electrical.MEGOHMS, EngineeringUnits.megohms},
                {EngineeringUnitsTypes.Electrical.SIEMENS, EngineeringUnits.siemens},
                {EngineeringUnitsTypes.Electrical.SIEMENS_PER_METER, EngineeringUnits.siemensPerMeter},
                {EngineeringUnitsTypes.Electrical.TESLAS, EngineeringUnits.teslas},
                {EngineeringUnitsTypes.Electrical.VOLTS, EngineeringUnits.volts},
                {EngineeringUnitsTypes.Electrical.MILLIVOLTS, EngineeringUnits.millivolts},
                {EngineeringUnitsTypes.Electrical.KILOVOLTS, EngineeringUnits.kilovolts},
                {EngineeringUnitsTypes.Electrical.MEGAVOLTS, EngineeringUnits.megavolts},
                {EngineeringUnitsTypes.Electrical.VOLT_AMPERES, EngineeringUnits.voltAmperes},
                {EngineeringUnitsTypes.Electrical.KILOVOLT_AMPERES, EngineeringUnits.kilovoltAmperes},
                {EngineeringUnitsTypes.Electrical.MEGAVOLT_AMPERES, EngineeringUnits.megavoltAmperes},
                {EngineeringUnitsTypes.Electrical.VOLT_AMPERES_REACTIVE, EngineeringUnits.voltAmperesReactive},
                {EngineeringUnitsTypes.Electrical.KILOVOLT_AMPERES_REACTIVE, EngineeringUnits.kilovoltAmperesReactive},
                {EngineeringUnitsTypes.Electrical.MEGAVOLT_AMPERES_REACTIVE, EngineeringUnits.megavoltAmperesReactive},
                {EngineeringUnitsTypes.Electrical.VOLTS_PER_DEGREE_KELVIN, EngineeringUnits.voltsPerDegreeKelvin},
                {EngineeringUnitsTypes.Electrical.VOLTS_PER_METER, EngineeringUnits.voltsPerMeter},
                {EngineeringUnitsTypes.Electrical.DEGREES_PHASE, EngineeringUnits.degreesPhase},
                {EngineeringUnitsTypes.Electrical.POWER_FACTOR, EngineeringUnits.powerFactor},
                {EngineeringUnitsTypes.Electrical.WEBERS, EngineeringUnits.webers},
                {EngineeringUnitsTypes.Energy.JOULES, EngineeringUnits.joules},
                {EngineeringUnitsTypes.Energy.KILOJOULES, EngineeringUnits.kilojoules},
                {EngineeringUnitsTypes.Energy.KILOJOULES_PER_KILOGRAM, EngineeringUnits.kilojoulesPerKilogram},
                {EngineeringUnitsTypes.Energy.MEGAJOULES, EngineeringUnits.megajoules},
                {EngineeringUnitsTypes.Energy.WATT_HOURS, EngineeringUnits.wattHours},
                {EngineeringUnitsTypes.Energy.KILOWATT_HOURS, EngineeringUnits.kilowattHours},
                {EngineeringUnitsTypes.Energy.MEGAWATT_HOURS, EngineeringUnits.megawattHours},
                {EngineeringUnitsTypes.Energy.BTUS, EngineeringUnits.btus},
                {EngineeringUnitsTypes.Energy.KILO_BTUS, EngineeringUnits.kiloBtus},
                {EngineeringUnitsTypes.Energy.MEGA_BTUS, EngineeringUnits.megaBtus},
                {EngineeringUnitsTypes.Energy.THERMS, EngineeringUnits.therms},
                {EngineeringUnitsTypes.Energy.TON_HOURS, EngineeringUnits.tonHours},
                {EngineeringUnitsTypes.Enthalpy.JOULES_PER_KILOGRAM_DRY_AIR, EngineeringUnits.joulesPerKilogramDryAir},
                {EngineeringUnitsTypes.Enthalpy.KILOJOULES_PER_KILOGRAM_DRY_AIR, EngineeringUnits.kilojoulesPerKilogramDryAir},
                {EngineeringUnitsTypes.Enthalpy.MEGAJOULES_PER_KILOGRAM_DRY_AIR, EngineeringUnits.megajoulesPerKilogramDryAir},
                {EngineeringUnitsTypes.Enthalpy.BTUS_PER_POUND_DRY_AIR, EngineeringUnits.btusPerPoundDryAir},
                {EngineeringUnitsTypes.Enthalpy.BTUS_PER_POUND, EngineeringUnits.btusPerPound},
                {EngineeringUnitsTypes.Entropy.JOULES_PER_DEGREE_KELVIN, EngineeringUnits.joulesPerDegreeKelvin},
                {EngineeringUnitsTypes.Entropy.KILOJOULES_PER_DEGREE_KELVIN, EngineeringUnits.kilojoulesPerDegreeKelvin},
                {EngineeringUnitsTypes.Entropy.MEGAJOULES_PER_DEGREE_KELVIN, EngineeringUnits.megajoulesPerDegreeKelvin},
                {EngineeringUnitsTypes.Entropy.JOULES_PER_KILOGRAM_DEGREE_KELVIN, EngineeringUnits.joulesPerKilogramDegreeKelvin},
                {EngineeringUnitsTypes.Force.NEWTON, EngineeringUnits.newton},
                {EngineeringUnitsTypes.Frequency.CYCLES_PER_HOUR, EngineeringUnits.cyclesPerHour},
                {EngineeringUnitsTypes.Frequency.CYCLES_PER_MINUTE, EngineeringUnits.cyclesPerMinute},
                {EngineeringUnitsTypes.Frequency.HERTZ, EngineeringUnits.hertz},
                {EngineeringUnitsTypes.Frequency.KILOHERTZ, EngineeringUnits.kilohertz},
                {EngineeringUnitsTypes.Frequency.MEGAHERTZ, EngineeringUnits.megahertz},
                {EngineeringUnitsTypes.Frequency.PER_HOUR, EngineeringUnits.perHour},
                {EngineeringUnitsTypes.Humidity.GRAMS_OF_WATER_PER_KILOGRAM_DRY_AIR, EngineeringUnits.gramsOfWaterPerKilogramDryAir},
                {EngineeringUnitsTypes.Humidity.PERCENT_RELATIVE_HUMIDITY, EngineeringUnits.percentRelativeHumidity},
                {EngineeringUnitsTypes.Length.MILLIMETERS, EngineeringUnits.millimeters},
                {EngineeringUnitsTypes.Length.CENTIMETERS, EngineeringUnits.centimeters},
                {EngineeringUnitsTypes.Length.METERS, EngineeringUnits.meters},
                {EngineeringUnitsTypes.Length.INCHES, EngineeringUnits.inches},
                {EngineeringUnitsTypes.Length.FEET, EngineeringUnits.feet},
                {EngineeringUnitsTypes.Light.CANDELAS, EngineeringUnits.candelas},
                {EngineeringUnitsTypes.Light.CANDELAS_PER_SQUARE_METER, EngineeringUnits.candelasPerSquareMeter},
                {EngineeringUnitsTypes.Light.WATTS_PER_SQUARE_FOOT, EngineeringUnits.wattsPerSquareFoot},
                {EngineeringUnitsTypes.Light.WATTS_PER_SQUARE_METER, EngineeringUnits.wattsPerSquareMeter},
                {EngineeringUnitsTypes.Light.LUMENS, EngineeringUnits.lumens},
                {EngineeringUnitsTypes.Light.LUXES, EngineeringUnits.luxes},
                {EngineeringUnitsTypes.Light.FOOT_CANDLES, EngineeringUnits.footCandles},
                {EngineeringUnitsTypes.Mass.KILOGRAMS, EngineeringUnits.kilograms},
                {EngineeringUnitsTypes.Mass.POUNDS_MASS, EngineeringUnits.poundsMass},
                {EngineeringUnitsTypes.Mass.TONS, EngineeringUnits.tons},
                {EngineeringUnitsTypes.MassFlow.GRAMS_PER_SECOND, EngineeringUnits.gramsPerSecond},
                {EngineeringUnitsTypes.MassFlow.GRAMS_PER_MINUTE, EngineeringUnits.gramsPerMinute},
                {EngineeringUnitsTypes.MassFlow.KILOGRAMS_PER_SECOND, EngineeringUnits.kilogramsPerSecond},
                {EngineeringUnitsTypes.MassFlow.KILOGRAMS_PER_MINUTE, EngineeringUnits.kilogramsPerMinute},
                {EngineeringUnitsTypes.MassFlow.KILOGRAMS_PER_HOUR, EngineeringUnits.kilogramsPerHour},
                {EngineeringUnitsTypes.MassFlow.POUNDS_MASS_PER_SECOND, EngineeringUnits.poundsMassPerSecond},
                {EngineeringUnitsTypes.MassFlow.POUNDS_MASS_PER_MINUTE, EngineeringUnits.poundsMassPerMinute},
                {EngineeringUnitsTypes.MassFlow.POUNDS_MASS_PER_HOUR, EngineeringUnits.poundsMassPerHour},
                {EngineeringUnitsTypes.MassFlow.TONS_PER_HOUR, EngineeringUnits.tonsPerHour},
                {EngineeringUnitsTypes.Power.MILLIWATTS, EngineeringUnits.milliwatts},
                {EngineeringUnitsTypes.Power.WATTS, EngineeringUnits.watts},
                {EngineeringUnitsTypes.Power.KILOWATTS, EngineeringUnits.kilowatts},
                {EngineeringUnitsTypes.Power.MEGAWATTS, EngineeringUnits.megawatts},
                {EngineeringUnitsTypes.Power.BTUS_PER_HOUR, EngineeringUnits.btusPerHour},
                {EngineeringUnitsTypes.Power.KILO_BTUS_PER_HOUR, EngineeringUnits.kiloBtusPerHour},
                {EngineeringUnitsTypes.Power.HORSEPOWER, EngineeringUnits.horsepower},
                {EngineeringUnitsTypes.Power.TONS_REFRIGERATION, EngineeringUnits.tonsRefrigeration},
                {EngineeringUnitsTypes.Pressure.PASCALS, EngineeringUnits.pascals},
                {EngineeringUnitsTypes.Pressure.HECTOPASCALS, EngineeringUnits.hectopascals},
                {EngineeringUnitsTypes.Pressure.KILOPASCALS, EngineeringUnits.kilopascals},
                {EngineeringUnitsTypes.Pressure.MILLIBARS, EngineeringUnits.millibars},
                {EngineeringUnitsTypes.Pressure.BARS, EngineeringUnits.bars},
                {EngineeringUnitsTypes.Pressure.POUNDS_FORCE_PER_SQUARE_INCH, EngineeringUnits.poundsForcePerSquareInch},
                {EngineeringUnitsTypes.Pressure.CENTIMETERS_OF_WATER, EngineeringUnits.centimetersOfWater},
                {EngineeringUnitsTypes.Pressure.INCHES_OF_WATER, EngineeringUnits.inchesOfWater},
                {EngineeringUnitsTypes.Pressure.MILLIMETERS_OF_MERCURY, EngineeringUnits.millimetersOfMercury},
                {EngineeringUnitsTypes.Pressure.CENTIMETERS_OF_MERCURY, EngineeringUnits.centimetersOfMercury},
                {EngineeringUnitsTypes.Pressure.INCHES_OF_MERCURY, EngineeringUnits.inchesOfMercury},
                {EngineeringUnitsTypes.Temperature.DEGREES_CELSIUS, EngineeringUnits.degreesCelsius},
                {EngineeringUnitsTypes.Temperature.DEGREES_KELVIN, EngineeringUnits.degreesKelvin},
                {EngineeringUnitsTypes.Temperature.DEGREES_KELVIN_PER_HOUR, EngineeringUnits.degreesKelvinPerHour},
                {EngineeringUnitsTypes.Temperature.DEGREES_KELVIN_PER_MINUTE, EngineeringUnits.degreesKelvinPerMinute},
                {EngineeringUnitsTypes.Temperature.DEGREES_FAHRENHEIT, EngineeringUnits.degreesFahrenheit},
                {EngineeringUnitsTypes.Temperature.DEGREE_DAYS_CELSIUS, EngineeringUnits.degreeDaysCelsius},
                {EngineeringUnitsTypes.Temperature.DEGREE_DAYS_FAHRENHEIT, EngineeringUnits.degreeDaysFahrenheit},
                {EngineeringUnitsTypes.Temperature.DELTA_DEGREES_FAHRENHEIT, EngineeringUnits.deltaDegreesFahrenheit},
                {EngineeringUnitsTypes.Temperature.DELTA_DEGREES_KELVIN, EngineeringUnits.deltaDegreesKelvin},
                {EngineeringUnitsTypes.Time.YEARS, EngineeringUnits.years},
                {EngineeringUnitsTypes.Time.MONTHS, EngineeringUnits.months},
                {EngineeringUnitsTypes.Time.WEEKS, EngineeringUnits.weeks},
                {EngineeringUnitsTypes.Time.DAYS, EngineeringUnits.days},
                {EngineeringUnitsTypes.Time.HOURS, EngineeringUnits.hours},
                {EngineeringUnitsTypes.Time.MINUTES, EngineeringUnits.minutes},
                {EngineeringUnitsTypes.Time.SECONDS, EngineeringUnits.seconds},
                {EngineeringUnitsTypes.Time.HUNDREDTHS_SECONDS, EngineeringUnits.hundredthsSeconds},
                {EngineeringUnitsTypes.Time.MILLISECONDS, EngineeringUnits.milliseconds},
                {EngineeringUnitsTypes.Torque.NEWTON_METERS, EngineeringUnits.newtonMeters},
                {EngineeringUnitsTypes.Velocity.MILLIMETERS_PER_SECOND, EngineeringUnits.millimetersPerSecond},
                {EngineeringUnitsTypes.Velocity.MILLIMETERS_PER_MINUTE, EngineeringUnits.millimetersPerMinute},
                {EngineeringUnitsTypes.Velocity.METERS_PER_SECOND, EngineeringUnits.metersPerSecond},
                {EngineeringUnitsTypes.Velocity.METERS_PER_MINUTE, EngineeringUnits.metersPerMinute},
                {EngineeringUnitsTypes.Velocity.METERS_PER_HOUR, EngineeringUnits.metersPerHour},
                {EngineeringUnitsTypes.Velocity.KILOMETERS_PER_HOUR, EngineeringUnits.kilometersPerHour},
                {EngineeringUnitsTypes.Velocity.FEET_PER_SECOND, EngineeringUnits.feetPerSecond},
                {EngineeringUnitsTypes.Velocity.FEET_PER_MINUTE, EngineeringUnits.feetPerMinute},
                {EngineeringUnitsTypes.Velocity.MILES_PER_HOUR, EngineeringUnits.milesPerHour},
                {EngineeringUnitsTypes.Volume.CUBIC_FEET, EngineeringUnits.cubicFeet},
                {EngineeringUnitsTypes.Volume.CUBIC_METERS, EngineeringUnits.cubicMeters},
                {EngineeringUnitsTypes.Volume.IMPERIAL_GALLONS, EngineeringUnits.imperialGallons},
                {EngineeringUnitsTypes.Volume.LITERS, EngineeringUnits.liters},
                {EngineeringUnitsTypes.Volume.US_GALLONS, EngineeringUnits.usGallons},
                {EngineeringUnitsTypes.VolumetricFlow.CUBIC_FEET_PER_SECOND, EngineeringUnits.cubicFeetPerSecond},
                {EngineeringUnitsTypes.VolumetricFlow.CUBIC_FEET_PER_MINUTE, EngineeringUnits.cubicFeetPerMinute},
                {EngineeringUnitsTypes.VolumetricFlow.CUBIC_METERS_PER_SECOND, EngineeringUnits.cubicMetersPerSecond},
                {EngineeringUnitsTypes.VolumetricFlow.CUBIC_METERS_PER_MINUTE, EngineeringUnits.cubicMetersPerMinute},
                {EngineeringUnitsTypes.VolumetricFlow.CUBIC_METERS_PER_HOUR, EngineeringUnits.cubicMetersPerHour},
                {EngineeringUnitsTypes.VolumetricFlow.IMPERIAL_GALLONS_PER_MINUTE, EngineeringUnits.imperialGallonsPerMinute},
                {EngineeringUnitsTypes.VolumetricFlow.LITERS_PER_SECOND, EngineeringUnits.litersPerSecond},
                {EngineeringUnitsTypes.VolumetricFlow.LITERS_PER_MINUTE, EngineeringUnits.litersPerMinute},
                {EngineeringUnitsTypes.VolumetricFlow.LITERS_PER_HOUR, EngineeringUnits.litersPerHour},
                {EngineeringUnitsTypes.VolumetricFlow.US_GALLONS_PER_MINUTE, EngineeringUnits.usGallonsPerMinute},
                {EngineeringUnitsTypes.DEGREES_ANGULAR, EngineeringUnits.degreesAngular},
                {EngineeringUnitsTypes.DEGREES_CELSIUS_PER_HOUR, EngineeringUnits.degreesCelsiusPerHour},
                {EngineeringUnitsTypes.DEGREES_CELSIUS_PER_MINUTE, EngineeringUnits.degreesCelsiusPerMinute},
                {EngineeringUnitsTypes.DEGREES_FAHRENHEIT_PER_HOUR, EngineeringUnits.degreesFahrenheitPerHour},
                {EngineeringUnitsTypes.DEGREES_FAHRENHEIT_PER_MINUTE, EngineeringUnits.degreesFahrenheitPerMinute},
                {EngineeringUnitsTypes.JOULE_SECONDS, EngineeringUnits.jouleSeconds},
                {EngineeringUnitsTypes.KILOGRAMS_PER_CUBIC_METER, EngineeringUnits.kilogramsPerCubicMeter},
                {EngineeringUnitsTypes.KILOWATT_HOURS_PER_SQUARE_METER, EngineeringUnits.kilowattHoursPerSquareMeter},
                {EngineeringUnitsTypes.KILOWATT_HOURS_PER_SQUARE_FOOT, EngineeringUnits.kilowattHoursPerSquareFoot},
                {EngineeringUnitsTypes.MEGAJOULES_PER_SQUARE_METER, EngineeringUnits.megajoulesPerSquareMeter},
                {EngineeringUnitsTypes.MEGAJOULES_PER_SQUARE_FOOT, EngineeringUnits.megajoulesPerSquareFoot},
                {EngineeringUnitsTypes.NO_UNITS, EngineeringUnits.noUnits},
                {EngineeringUnitsTypes.NEWTON_SECONDS, EngineeringUnits.newtonSeconds},
                {EngineeringUnitsTypes.NEWTONS_PER_METER, EngineeringUnits.newtonsPerMeter},
                {EngineeringUnitsTypes.PARTS_PER_MILLION, EngineeringUnits.partsPerMillion},
                {EngineeringUnitsTypes.PARTS_PER_BILLION, EngineeringUnits.partsPerBillion},
                {EngineeringUnitsTypes.PERCENT, EngineeringUnits.percent},
                {EngineeringUnitsTypes.PERCENT_OBSCURATION_PER_FOOT, EngineeringUnits.percentObscurationPerFoot},
                {EngineeringUnitsTypes.PERCENT_OBSCURATION_PER_METER, EngineeringUnits.percentObscurationPerMeter},
                {EngineeringUnitsTypes.PERCENT_PER_SECOND, EngineeringUnits.percentPerSecond},
                {EngineeringUnitsTypes.PER_MINUTE, EngineeringUnits.perMinute},
                {EngineeringUnitsTypes.PER_SECOND, EngineeringUnits.perSecond},
                {EngineeringUnitsTypes.PSI_PER_DEGREE_FAHRENHEIT, EngineeringUnits.psiPerDegreeFahrenheit},
                {EngineeringUnitsTypes.RADIANS, EngineeringUnits.radians},
                {EngineeringUnitsTypes.RADIANS_PER_SECOND, EngineeringUnits.radiansPerSecond},
                {EngineeringUnitsTypes.REVOLUTIONS_PER_MINUTE, EngineeringUnits.revolutionsPerMinute},
                {EngineeringUnitsTypes.SQUARE_METERS_PER_NEWTON, EngineeringUnits.squareMetersPerNewton},
                {EngineeringUnitsTypes.WATTS_PER_METER_PER_DEGREE_KELVIN, EngineeringUnits.wattsPerMeterPerDegreeKelvin},
                {EngineeringUnitsTypes.WATTS_PER_SQUARE_METER_DEGREE_KELVIN, EngineeringUnits.wattsPerSquareMeterDegreeKelvin}

        };
    }

    private final EngineeringUnits engineeringUnitExpected;
    private final EngineeringUnit engineeringUnit;


    public EngineeringUnitsTypesTest(EngineeringUnit engineeringUnit, EngineeringUnits engineeringUnitExpected) {
        this.engineeringUnit = engineeringUnit;
        this.engineeringUnitExpected = engineeringUnitExpected;
    }

    @Test
    public void getValue() {

        //then:
        Assert.assertEquals(engineeringUnitExpected.intValue(), engineeringUnit.getValue());
    }

    @Test
    public void getName() {

        //then:
        Assert.assertEquals(engineeringUnitExpected.toString(), engineeringUnit.getName());
    }

}