package com.serotonin.mango.daoCache;


public enum Daos {
    VIEW_DAO,
    SCRIPT_DAO,
    DATA_POINT_DAO,
    USER_DAO,
    USERS_PROFILE_DAO,
    WATCH_LIST_DAO,
    EVENT_DAO,
    MAILING_LIST_DAO,
    POINT_LINK_DAO,
    REPORT_DAO,
    DATA_SOURCE_DAO,
    MAINTENANCE_EVENT_DAO,
    COMPOUND_EVENT_DETECTOR_DAO,
    PUBLISHER_DAO,
    POINT_VALUE_DAO,
    SCHEDULED_EVENT_DAO;
}
