export const DataTypes = {
	UNKNOWN: 0,
	BINARY: 1,
	MULTISTATE: 2,
	NUMERIC: 3,
	APLHANUMERIC: 4,
};

export const DataChangeTypes = {
	ALTERNATE_BOOLEAN: 1,
	BROWNIAN: 2,
	INCREMENT_ANALOG: 3,
	INCREMENT_MULTISTATE: 4,
	NO_CHANGE: 5,
	RANDOM_ANALOG: 6,
	RANDOM_BOOLEAN: 7,
	RANDOM_MULTISTATE: 8,
	ANALOG_ATTRACTOR: 9,
};
